// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: route.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_route_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "route.server",
		Tag:           "bytes,50001,opt,name=server",
		Filename:      "route.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string server = 50001;
	E_Server = &file_route_proto_extTypes[0]
)

var File_route_proto protoreflect.FileDescriptor

const file_route_proto_rawDesc = "" +
	"\n" +
	"\vroute.proto\x12\x05route\x1a google/protobuf/descriptor.proto:6\n" +
	"\x06server\x12\x1c.google.protobuf.FileOptions\x18ц\x03 \x01(\tR\x06serverB\tZ\a/protosb\x06proto3"

var file_route_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil), // 0: google.protobuf.FileOptions
}
var file_route_proto_depIdxs = []int32{
	0, // 0: route.server:extendee -> google.protobuf.FileOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_route_proto_init() }
func file_route_proto_init() {
	if File_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_proto_rawDesc), len(file_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_route_proto_goTypes,
		DependencyIndexes: file_route_proto_depIdxs,
		ExtensionInfos:    file_route_proto_extTypes,
	}.Build()
	File_route_proto = out.File
	file_route_proto_goTypes = nil
	file_route_proto_depIdxs = nil
}
