// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: cluster.proto

package clusterpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type N2MOnHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Frontend      bool                   `protobuf:"varint,3,opt,name=Frontend,proto3" json:"Frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnHandshake) Reset() {
	*x = N2MOnHandshake{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnHandshake) ProtoMessage() {}

func (x *N2MOnHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnHandshake.ProtoReflect.Descriptor instead.
func (*N2MOnHandshake) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *N2MOnHandshake) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *N2MOnHandshake) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *N2MOnHandshake) GetFrontend() bool {
	if x != nil {
		return x.Frontend
	}
	return false
}

type N2MOnSessionBind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	UID           string                 `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Servers       map[string]string      `protobuf:"bytes,3,rep,name=Servers,proto3" json:"Servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnSessionBind) Reset() {
	*x = N2MOnSessionBind{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnSessionBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnSessionBind) ProtoMessage() {}

func (x *N2MOnSessionBind) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnSessionBind.ProtoReflect.Descriptor instead.
func (*N2MOnSessionBind) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *N2MOnSessionBind) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *N2MOnSessionBind) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *N2MOnSessionBind) GetServers() map[string]string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type N2MOnSessionDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnSessionDisconnected) Reset() {
	*x = N2MOnSessionDisconnected{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnSessionDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnSessionDisconnected) ProtoMessage() {}

func (x *N2MOnSessionDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnSessionDisconnected.ProtoReflect.Descriptor instead.
func (*N2MOnSessionDisconnected) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *N2MOnSessionDisconnected) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type N2MOnPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     []string               `protobuf:"bytes,1,rep,name=SessionID,proto3" json:"SessionID,omitempty"`
	Plyload       []byte                 `protobuf:"bytes,2,opt,name=Plyload,proto3" json:"Plyload,omitempty"`
	MsgID         int32                  `protobuf:"varint,3,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnPush) Reset() {
	*x = N2MOnPush{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnPush) ProtoMessage() {}

func (x *N2MOnPush) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnPush.ProtoReflect.Descriptor instead.
func (*N2MOnPush) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *N2MOnPush) GetSessionID() []string {
	if x != nil {
		return x.SessionID
	}
	return nil
}

func (x *N2MOnPush) GetPlyload() []byte {
	if x != nil {
		return x.Plyload
	}
	return nil
}

func (x *N2MOnPush) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\acluster\"P\n" +
	"\x0eN2MOnHandshake\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFrontend\x18\x03 \x01(\bR\bFrontend\"\xc0\x01\n" +
	"\x10N2MOnSessionBind\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\tR\x03UID\x12@\n" +
	"\aServers\x18\x03 \x03(\v2&.cluster.N2MOnSessionBind.ServersEntryR\aServers\x1a:\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x18N2MOnSessionDisconnected\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\"Y\n" +
	"\tN2MOnPush\x12\x1c\n" +
	"\tSessionID\x18\x01 \x03(\tR\tSessionID\x12\x18\n" +
	"\aPlyload\x18\x02 \x01(\fR\aPlyload\x12\x14\n" +
	"\x05MsgID\x18\x03 \x01(\x05R\x05MsgIDB\fZ\n" +
	"./;clusterb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cluster_proto_goTypes = []any{
	(*N2MOnHandshake)(nil),           // 0: cluster.N2MOnHandshake
	(*N2MOnSessionBind)(nil),         // 1: cluster.N2MOnSessionBind
	(*N2MOnSessionDisconnected)(nil), // 2: cluster.N2MOnSessionDisconnected
	(*N2MOnPush)(nil),                // 3: cluster.N2MOnPush
	nil,                              // 4: cluster.N2MOnSessionBind.ServersEntry
}
var file_cluster_proto_depIdxs = []int32{
	4, // 0: cluster.N2MOnSessionBind.Servers:type_name -> cluster.N2MOnSessionBind.ServersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
