// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: cluster.proto

package cluster

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type N2MSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	MsgID         int32                  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Plyload       []byte                 `protobuf:"bytes,3,opt,name=Plyload,proto3" json:"Plyload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MSend) Reset() {
	*x = N2MSend{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MSend) ProtoMessage() {}

func (x *N2MSend) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MSend.ProtoReflect.Descriptor instead.
func (*N2MSend) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *N2MSend) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *N2MSend) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *N2MSend) GetPlyload() []byte {
	if x != nil {
		return x.Plyload
	}
	return nil
}

type N2MOnConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Frontend      bool                   `protobuf:"varint,3,opt,name=Frontend,proto3" json:"Frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnConnection) Reset() {
	*x = N2MOnConnection{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnConnection) ProtoMessage() {}

func (x *N2MOnConnection) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnConnection.ProtoReflect.Descriptor instead.
func (*N2MOnConnection) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *N2MOnConnection) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *N2MOnConnection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *N2MOnConnection) GetFrontend() bool {
	if x != nil {
		return x.Frontend
	}
	return false
}

type M2NOnConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Frontend      bool                   `protobuf:"varint,3,opt,name=Frontend,proto3" json:"Frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2NOnConnection) Reset() {
	*x = M2NOnConnection{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2NOnConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2NOnConnection) ProtoMessage() {}

func (x *M2NOnConnection) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2NOnConnection.ProtoReflect.Descriptor instead.
func (*M2NOnConnection) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *M2NOnConnection) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *M2NOnConnection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *M2NOnConnection) GetFrontend() bool {
	if x != nil {
		return x.Frontend
	}
	return false
}

type N2MOnSessionBindServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	UID           int64                  `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Servers       map[string]string      `protobuf:"bytes,3,rep,name=Servers,proto3" json:"Servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnSessionBindServer) Reset() {
	*x = N2MOnSessionBindServer{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnSessionBindServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnSessionBindServer) ProtoMessage() {}

func (x *N2MOnSessionBindServer) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnSessionBindServer.ProtoReflect.Descriptor instead.
func (*N2MOnSessionBindServer) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *N2MOnSessionBindServer) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *N2MOnSessionBindServer) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *N2MOnSessionBindServer) GetServers() map[string]string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type N2MOnSessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MOnSessionClose) Reset() {
	*x = N2MOnSessionClose{}
	mi := &file_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MOnSessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MOnSessionClose) ProtoMessage() {}

func (x *N2MOnSessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MOnSessionClose.ProtoReflect.Descriptor instead.
func (*N2MOnSessionClose) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *N2MOnSessionClose) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type N2MNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     []int64                `protobuf:"varint,1,rep,packed,name=SessionID,proto3" json:"SessionID,omitempty"`
	Plyload       []byte                 `protobuf:"bytes,2,opt,name=Plyload,proto3" json:"Plyload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N2MNotify) Reset() {
	*x = N2MNotify{}
	mi := &file_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N2MNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2MNotify) ProtoMessage() {}

func (x *N2MNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2MNotify.ProtoReflect.Descriptor instead.
func (*N2MNotify) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *N2MNotify) GetSessionID() []int64 {
	if x != nil {
		return x.SessionID
	}
	return nil
}

func (x *N2MNotify) GetPlyload() []byte {
	if x != nil {
		return x.Plyload
	}
	return nil
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\acluster\"W\n" +
	"\aN2MSend\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x14\n" +
	"\x05MsgID\x18\x02 \x01(\x05R\x05MsgID\x12\x18\n" +
	"\aPlyload\x18\x03 \x01(\fR\aPlyload\"Q\n" +
	"\x0fN2MOnConnection\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFrontend\x18\x03 \x01(\bR\bFrontend\"Q\n" +
	"\x0fM2NOnConnection\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFrontend\x18\x03 \x01(\bR\bFrontend\"\xcc\x01\n" +
	"\x16N2MOnSessionBindServer\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\x03R\x03UID\x12F\n" +
	"\aServers\x18\x03 \x03(\v2,.cluster.N2MOnSessionBindServer.ServersEntryR\aServers\x1a:\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x11N2MOnSessionClose\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\"C\n" +
	"\tN2MNotify\x12\x1c\n" +
	"\tSessionID\x18\x01 \x03(\x03R\tSessionID\x12\x18\n" +
	"\aPlyload\x18\x02 \x01(\fR\aPlyloadB\fZ\n" +
	"./;clusterb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cluster_proto_goTypes = []any{
	(*N2MSend)(nil),                // 0: cluster.N2MSend
	(*N2MOnConnection)(nil),        // 1: cluster.N2MOnConnection
	(*M2NOnConnection)(nil),        // 2: cluster.M2NOnConnection
	(*N2MOnSessionBindServer)(nil), // 3: cluster.N2MOnSessionBindServer
	(*N2MOnSessionClose)(nil),      // 4: cluster.N2MOnSessionClose
	(*N2MNotify)(nil),              // 5: cluster.N2MNotify
	nil,                            // 6: cluster.N2MOnSessionBindServer.ServersEntry
}
var file_cluster_proto_depIdxs = []int32{
	6, // 0: cluster.N2MOnSessionBindServer.Servers:type_name -> cluster.N2MOnSessionBindServer.ServersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
